version: '3.1' 

# Makefile has default variables set

services:

  install:
    container_name: 
        install
    build: 
        .
    image:
        socat/install:v${SOCAT_VERSION}
    volumes:
        - socat_base:/var/socat
        - socat_share:/var/socat/share
        - socat_db:/var/socat/db
    environment: 
        SOCAT_VERSION: ${SOCAT_VERSION}

  postgres:
    build: 
        ./postgres
    image:
        socat/postgres:v${SOCAT_VERSION}
    hostname: 
        postgres
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - socat_db:/var/lib/postgresql/data
        - socat_share:/var/share
    restart:
        unless-stopped
    networks:
        - socat_net

  pgadmin:
    build: 
        ./pgadmin
    image:
        socat/pgadmin:v${SOCAT_VERSION}
    hostname: 
        pgadmin
    depends_on:
        - postgres
    ports:
        - "80:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: ${POSTGRES_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - socat_share:/var/share
    restart:
        unless-stopped
    networks:
        - socat_net

networks:
  socat_net:
        driver: bridge

volumes:
  socat_base:
    driver: local
    driver_opts:
      type: none
      device: ${SOCAT_HOME}
      o: bind
  socat_db:
    driver: local
    driver_opts:
      type: none
      device: ${SOCAT_DB}
      o: bind
  socat_share:
    driver: local
    driver_opts:
      type: none
      device: ${SOCAT_SHARE}
      o: bind
